version: "3.7"

services:
  api:
    image: python:3      
    volumes: 
      - ./:/usr/src/app
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    command: bash -c "python api_server.py"
  
  client: 
    image: python:3
    depends_on: 
        - api
    volumes: 
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "pip install requests && python api_client.py"
